/**
 * HMRManager — manages Hot Module Replacement for the live preview iframe.
 *
 * Strategy:
 * 1. When new transpiled code arrives, attempt a lightweight HMR update by
 *    posting a `hmr:update` message into the preview iframe via postMessage.
 * 2. The preview iframe's module script listens for that message and calls
 *    the registered hot-accept handler if one exists.
 * 3. If HMR is not acknowledged within HMR_ACK_TIMEOUT_MS the manager falls
 *    back to a full reload by bumping the iframe `src` (via srcDoc reassign).
 *
 * HMR is a best-effort optimisation. It preserves React component state for
 * simple single-component updates. Multi-file or complex dependency changes
 * always fall back to a full reload.
 *
 * Usage:
 *   const manager = new HMRManager(iframeEl);
 *   manager.update(newHtml, transpiledCode);
 *   manager.destroy();
 */

export interface HMRUpdatePayload {
  type: "hmr:update";
  code: string;
  timestamp: number;
}

export interface HMRAckPayload {
  type: "hmr:ack";
  timestamp: number;
}

type IncomingMessage = HMRAckPayload | { type: string };

const HMR_ACK_TIMEOUT_MS = 1_500;

export class HMRManager {
  private iframe: HTMLIFrameElement;
  private pendingAckTimer: ReturnType<typeof setTimeout> | null = null;
  private pendingTimestamp: number | null = null;
  private onFullReload: ((html: string) => void) | null = null;
  private latestHtml = "";
  private destroyed = false;

  constructor(iframe: HTMLIFrameElement, onFullReload?: (html: string) => void) {
    this.iframe = iframe;
    this.onFullReload = onFullReload ?? null;
    window.addEventListener("message", this.handleMessage);
  }

  /**
   * Push an update to the preview.
   *
   * @param html    Full HTML document to use when a full reload is needed.
   * @param code    The new transpiled JS module source for the HMR hot path.
   */
  update(html: string, code: string): void {
    if (this.destroyed) return;

    this.latestHtml = html;
    this.cancelPendingAck();

    const timestamp = Date.now();
    this.pendingTimestamp = timestamp;

    const payload: HMRUpdatePayload = { type: "hmr:update", code, timestamp };

    try {
      this.iframe.contentWindow?.postMessage(payload, "*");
    } catch {
      // Cross-origin or not loaded yet — fall back immediately
      this.triggerFullReload();
      return;
    }

    // Wait for ack; fall back if none arrives in time
    this.pendingAckTimer = setTimeout(() => {
      this.triggerFullReload();
    }, HMR_ACK_TIMEOUT_MS);
  }

  destroy(): void {
    this.destroyed = true;
    this.cancelPendingAck();
    window.removeEventListener("message", this.handleMessage);
  }

  private handleMessage = (event: MessageEvent): void => {
    if (this.destroyed) return;
    if (event.source !== this.iframe.contentWindow) return;

    const data = event.data as IncomingMessage;
    if (data?.type !== "hmr:ack") return;

    const ack = data as HMRAckPayload;
    if (ack.timestamp === this.pendingTimestamp) {
      this.cancelPendingAck();
    }
  };

  private cancelPendingAck(): void {
    if (this.pendingAckTimer !== null) {
      clearTimeout(this.pendingAckTimer);
      this.pendingAckTimer = null;
    }
    this.pendingTimestamp = null;
  }

  private triggerFullReload(): void {
    this.cancelPendingAck();
    if (this.onFullReload) {
      this.onFullReload(this.latestHtml);
    }
  }
}

// ---------------------------------------------------------------------------
// HMR bootstrap snippet — injected into preview HTML by buildPreviewHtml.
// Paste this verbatim inside the preview's <script type="module"> block
// (already included in the HTML generated by useTranspile.buildPreviewHtml).
// ---------------------------------------------------------------------------

export const HMR_BOOTSTRAP_SCRIPT = `
(function() {
  let _hotAcceptHandler = null;

  // Register a hot-accept callback from app code.
  // Usage inside preview: globalThis.__hmr__.accept((newModule) => { ... });
  globalThis.__hmr__ = {
    accept(handler) { _hotAcceptHandler = handler; },
  };

  window.addEventListener("message", async (event) => {
    if (!event.data || event.data.type !== "hmr:update") return;
    const { code, timestamp } = event.data;

    try {
      if (typeof _hotAcceptHandler === "function") {
        // Evaluate the new module and call the handler
        const blob = new Blob([code], { type: "text/javascript" });
        const url = URL.createObjectURL(blob);
        const mod = await import(url);
        URL.revokeObjectURL(url);
        _hotAcceptHandler(mod);
      } else {
        // No handler registered — perform a full in-page re-render instead
        const blob = new Blob([code], { type: "text/javascript" });
        const url = URL.createObjectURL(blob);
        await import(url);
        URL.revokeObjectURL(url);
      }
      // Acknowledge the update so the HMRManager doesn't fall back to full reload
      event.source.postMessage({ type: "hmr:ack", timestamp }, "*");
    } catch (err) {
      console.error("[HMR] Update failed:", err);
      // Do NOT ack — the manager will trigger a full reload as fallback
    }
  });
})();
`;
