import {
  Accessibility,
  AlertTriangle,
  BarChart,
  Bell,
  BookOpen,
  Bot,
  Briefcase,
  ClipboardList,
  Code,
  Component,
  Dice6,
  FileText,
  Fingerprint,
  FlaskConical,
  GitBranch,
  GitPullRequest,
  Globe,
  Image,
  Layers,
  Layout,
  LayoutGrid,
  Loader,
  Megaphone,
  MessageSquare,
  MousePointerClick,
  Music,
  Network,
  Palette,
  PanelTop,
  Play,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Sparkle,
  Sparkles,
  SplitSquareHorizontal,
  Store,
  Table2,
  Terminal,
  Trophy,
  Tv,
  Type,
  Zap,
} from "lucide-react";

export const storybookIconMap = {
  Sparkles,
  Palette,
  Type,
  MousePointerClick,
  Component,
  SplitSquareHorizontal,
  Bell,
  Loader,
  PanelTop,
  Accessibility,
  Table2,
  LayoutGrid,
  ShoppingBag,
  Layers,
  ShieldCheck,
  AlertTriangle,
  BookOpen,
  Briefcase,
  Sparkle,
  Trophy,
  Terminal,
  Globe,
  MessageSquare,
  Bot,
  GitBranch,
  Image,
  Store,
  Zap,
  Code,
  ClipboardList,
  BarChart,
  Play,
  Music,
  Layout,
  Megaphone,
  FileText,
  Share2,
  Settings,
  FlaskConical,
  Dice6,
  Fingerprint,
  Tv,
  GitPullRequest,
  Network,
};

export const colorPalette = {
  brand: [
    {
      name: "spike.land Cyan",
      var: "--pixel-cyan",
      hex: "#00E5FF",
      desc: "Primary brand accent colors",
      role: "Primary",
      contrastPass: true,
    },
    {
      name: "spike.land Fuchsia",
      var: "--pixel-fuchsia",
      hex: "#FF00FF",
      desc: "Secondary accent",
      role: "Secondary",
      contrastPass: true,
    },
  ],
  dark: [
    {
      name: "Surface Blue",
      var: "--surface-blue",
      hex: "#112244",
      desc: "Card backgrounds",
    },
    {
      name: "Border",
      var: "--border-dark",
      hex: "#221144",
      desc: "Primary borders",
    },
    {
      name: "Border Item",
      var: "--border-item",
      hex: "#222244",
      desc: "Item borders",
    },
    {
      name: "Deep Space",
      var: "--background",
      hex: "#08081C",
      desc: "Dark background",
    },
    {
      name: "Text Muted",
      var: "--muted-foreground",
      hex: "#A0A0C0",
      desc: "Secondary text",
    },
  ],
  light: [
    {
      name: "Clean White",
      var: "--background",
      hex: "#FFFFFF",
      desc: "Light background",
    },
    {
      name: "Light Surface",
      var: "--card",
      hex: "#F4F6F8",
      desc: "Light cards",
    },
    {
      name: "Carbon Text",
      var: "--foreground",
      hex: "#12121C",
      desc: "Primary text",
    },
    {
      name: "Grid Grey",
      var: "--border",
      hex: "#DCE0E8",
      desc: "Light borders",
    },
  ],
};

export const logoSizes = ["sm", "md", "lg", "xl"] as const;
export const logoVariants = ["icon", "horizontal", "stacked"] as const;
export const buttonVariants = [
  "default",
  "secondary",
  "outline",
  "ghost",
  "destructive",
  "link",
] as const;
export const buttonSizes = ["sm", "default", "lg", "icon"] as const;

export const storybookSections = [
  {
    id: "brand",
    label: "Brand",
    category: "Foundation",
    description: "Logo variants, sizes, and the spike.land AI Spark logo",
    icon: "Sparkles",
  },
  {
    id: "colors",
    label: "Colors",
    category: "Foundation",
    description: "Color palette, brand colors, dark/light modes, glow effects",
    icon: "Palette",
  },
  {
    id: "typography",
    label: "Typography",
    category: "Foundation",
    description: "Font families, heading scale, text colors",
    icon: "Type",
  },
  {
    id: "surfaces",
    label: "Surfaces",
    category: "Foundation",
    description: "Glass-morphism tiers, elevation system, and transparency",
    icon: "Layers",
  },
  {
    id: "animations",
    label: "Animations",
    category: "Foundation",
    description: "Transitions, micro-interactions, loading states, and timing tokens",
    icon: "Play",
  },
  {
    id: "buttons",
    label: "Buttons",
    category: "Actions",
    description: "Button variants, sizes, states, loading indicators",
    icon: "MousePointerClick",
  },
  {
    id: "components",
    label: "Components",
    category: "Elements",
    description: "Cards, badges, inputs, accordion, tabs, textarea, tooltip, slider",
    icon: "Component",
  },
  {
    id: "data-display",
    label: "Data Display",
    category: "Data",
    description: "Tables, toggle groups, and copy buttons",
    icon: "Table2",
  },
  {
    id: "layout",
    label: "Layout",
    category: "Structure",
    description: "Masonry grid, text overlays, and zoom controls",
    icon: "LayoutGrid",
  },
  {
    id: "comparison",
    label: "Comparison",
    category: "Elements",
    description: "Image comparison slider, comparison view toggle",
    icon: "SplitSquareHorizontal",
  },
  {
    id: "feedback",
    label: "Feedback",
    category: "Status",
    description: "Toast notifications, alerts, semantic state colors",
    icon: "Bell",
  },
  {
    id: "loading",
    label: "Loading",
    category: "Status",
    description: "Skeleton loaders, progress bars, spinners/animations",
    icon: "Loader",
  },
  {
    id: "modals",
    label: "Modals",
    category: "Overlays",
    description: "Dialogs, dropdown menus, sheets, alert dialogs",
    icon: "PanelTop",
  },
  {
    id: "accessibility",
    label: "Accessibility",
    category: "Principles",
    description: "Contrast checker, keyboard navigation, ARIA attributes",
    icon: "Accessibility",
  },
  {
    id: "merch",
    label: "Merch",
    category: "Features",
    description: "Print-on-demand merchandise components",
    icon: "ShoppingBag",
  },
  {
    id: "photo-mix",
    label: "PhotoMix",
    category: "Features",
    description: "Photo mixing and blending components",
    icon: "Layers",
  },
  {
    id: "enhance",
    label: "Enhance",
    category: "Features",
    description:
      "Image enhancement workflows - comparison slider, tier selection, batch processing",
    icon: "Sparkle",
  },
  {
    id: "auth",
    label: "Auth",
    category: "Systems",
    description: "Authentication components, buttons, and user avatars",
    icon: "ShieldCheck",
  },
  {
    id: "errors",
    label: "Errors",
    category: "Systems",
    description: "Error handling components and error boundaries",
    icon: "AlertTriangle",
  },
  // --- New sections ---
  {
    id: "blog",
    label: "Blog",
    category: "Content",
    description: "Blog cards, headers, poll components, and interactive article demos",
    icon: "BookOpen",
  },
  {
    id: "career",
    label: "Career",
    category: "Apps",
    description:
      "Career navigator with job listings, skill gap analysis, salary charts, and occupation cards",
    icon: "Briefcase",
  },
  {
    id: "clean",
    label: "CleanSweep",
    category: "Apps",
    description:
      "Gamified cleaning app - task cards, progress bars, achievement system, streak displays",
    icon: "Sparkle",
  },
  {
    id: "arena",
    label: "Arena",
    category: "Apps",
    description:
      "Gaming & competition - leaderboard, challenge cards, phase steps, live stream badges",
    icon: "Trophy",
  },
  {
    id: "mcp",
    label: "MCP Explorer",
    category: "Platform",
    description:
      "Model Context Protocol tools - tool cards, category grid, terminal, playground, config snippets",
    icon: "Terminal",
  },
  {
    id: "landing",
    label: "Landing",
    category: "Marketing",
    description:
      "Landing page sections - hero, three pillars, app showcase, blog preview, create CTA",
    icon: "Globe",
  },
  {
    id: "chat",
    label: "Chat",
    category: "Platform",
    description:
      "Chat & messaging - markdown renderer, tool call cards, image annotator, site chat widget",
    icon: "MessageSquare",
  },
  {
    id: "agents",
    label: "Agents",
    category: "Platform",
    description: "Agent management - agent cards, catalog grid, stats, rename dialog, task sender",
    icon: "Bot",
  },
  {
    id: "state-machine",
    label: "State Machine",
    category: "Apps",
    description:
      "Visual state machine builder - state graph, editor panels, simulation, template library",
    icon: "GitBranch",
  },
  {
    id: "canvas",
    label: "Canvas",
    category: "Apps",
    description:
      "Album & canvas editor - masonry grid, QR code panel, slideshow, smart grid, zoom slider",
    icon: "Image",
  },
  {
    id: "store-apps",
    label: "App Store",
    category: "Platform",
    description:
      "App store marketplace - featured carousel, category tabs, app grid, developer CTA",
    icon: "Store",
  },
  {
    id: "bazdmeg",
    label: "Bazdmeg",
    category: "Platform",
    description:
      "AI workflow orchestration - quality checkpoints, effort split, hourglass model, chat interface",
    icon: "Zap",
  },
  {
    id: "create",
    label: "Creator",
    category: "Apps",
    description:
      "App creator - composer box, skill badges, live preview, streaming app, related apps",
    icon: "Code",
  },
  {
    id: "forms",
    label: "Forms",
    category: "Elements",
    description: "Form patterns - multi-step forms, validation states, form layouts, field groups",
    icon: "ClipboardList",
  },
  {
    id: "infographic",
    label: "Infographic",
    category: "Content",
    description:
      "Data visualization - animated counters, progress gauges, interactive checklists, glass cards",
    icon: "BarChart",
  },
  {
    id: "audio-studio",
    label: "Audio Studio",
    category: "Apps",
    description: "Audio production - track list, mixer faders, transport controls, project cards",
    icon: "Music",
  },
  {
    id: "page-builder",
    label: "Page Builder",
    category: "Apps",
    description:
      "Visual page builder - block palette, canvas preview, publish toolbar, project cards",
    icon: "Layout",
  },
  {
    id: "brand-command",
    label: "Brand Command",
    category: "Apps",
    description:
      "Brand management - voice score gauge, guardrails panel, copy generator, competitor cards",
    icon: "Megaphone",
  },
  {
    id: "content-hub",
    label: "Content Hub",
    category: "Apps",
    description: "Content management - post cards, status badges, editor preview, metrics rows",
    icon: "FileText",
  },
  {
    id: "social-autopilot",
    label: "Social Autopilot",
    category: "Apps",
    description:
      "Social scheduling - schedule calendar, post cards, best-times chart, gap detection",
    icon: "Share2",
  },
  {
    id: "spike-land-admin",
    label: "Spike Land Admin",
    category: "Apps",
    description: "Admin dashboard - stats bar, user table rows, system health cards, activity feed",
    icon: "Settings",
  },
  {
    id: "qa-studio",
    label: "QA Studio",
    category: "Apps",
    description:
      "Quality assurance - test run cards, a11y reports, screenshot viewer, network table",
    icon: "FlaskConical",
  },
  {
    id: "tabletop-sim",
    label: "Tabletop Sim",
    category: "Apps",
    description: "Virtual tabletop - game room cards, dice roller, player avatars, game board",
    icon: "Dice6",
  },
  {
    id: "be-uniq",
    label: "beUniq",
    category: "Apps",
    description:
      "Personality discovery - question cards, uniqueness score, tag cloud, progress tracker",
    icon: "Fingerprint",
  },
  {
    id: "code-review-agent",
    label: "Code Review Agent",
    category: "Apps",
    description: "AI code review - review cards, issue rows, complexity badges, rules panel",
    icon: "GitPullRequest",
  },
  {
    id: "ai-orchestrator",
    label: "AI Orchestrator",
    category: "Apps",
    description:
      "Agent orchestration - agent topology, task delegation, swarm stats, agent node cards",
    icon: "Network",
  },
] as const;
