/**
 * State Machine Templates: E-Commerce, IoT & Hardware, Gaming
 */

import {
  Activity,
  CreditCard,
  Gamepad2,
  Layers,
  ShoppingCart,
  Thermometer,
  Truck,
  Wifi,
} from "lucide-react";
import type { TemplateDefinition } from "../TemplateLibrary";

export const ECOMMERCE_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Shopping Cart",
    description: "Cart flow from empty to confirmed purchase",
    icon: <ShoppingCart className="w-5 h-5" />,
    color: "#f59e0b",
    category: "E-Commerce",
    initialState: "empty",
    states: [
      { id: "empty", type: "atomic" },
      { id: "has_items", type: "atomic" },
      { id: "checkout", type: "atomic" },
      { id: "payment", type: "atomic" },
      { id: "confirmed", type: "final" },
    ],
    transitions: [
      { source: "empty", target: "has_items", event: "ADD_ITEM" },
      { source: "has_items", target: "has_items", event: "ADD_ITEM" },
      {
        source: "has_items",
        target: "empty",
        event: "REMOVE_ITEM",
        guard_expression: "context.itemCount == 1",
      },
      {
        source: "has_items",
        target: "has_items",
        event: "REMOVE_ITEM",
        guard_expression: "context.itemCount > 1",
      },
      { source: "has_items", target: "checkout", event: "CHECKOUT" },
      { source: "checkout", target: "has_items", event: "BACK" },
      { source: "checkout", target: "payment", event: "PAY" },
      { source: "payment", target: "confirmed", event: "PAYMENT_SUCCESS" },
      { source: "payment", target: "checkout", event: "PAYMENT_FAILURE" },
    ],
    context: { items: [], itemCount: 0, total: 0 },
  },
  {
    name: "Order Fulfillment",
    description: "Order placed \u2192 packed \u2192 shipped \u2192 delivered",
    icon: <Truck className="w-5 h-5" />,
    color: "#10b981",
    category: "E-Commerce",
    initialState: "placed",
    states: [
      { id: "placed", type: "atomic" },
      { id: "processing", type: "atomic" },
      { id: "packed", type: "atomic" },
      { id: "shipped", type: "atomic" },
      { id: "delivered", type: "final" },
      { id: "cancelled", type: "final" },
      { id: "returned", type: "final" },
    ],
    transitions: [
      { source: "placed", target: "processing", event: "PROCESS" },
      { source: "placed", target: "cancelled", event: "CANCEL" },
      { source: "processing", target: "packed", event: "PACK" },
      { source: "processing", target: "cancelled", event: "CANCEL" },
      { source: "packed", target: "shipped", event: "SHIP" },
      { source: "shipped", target: "delivered", event: "DELIVER" },
      { source: "delivered", target: "returned", event: "RETURN" },
    ],
    context: { trackingNumber: null, carrier: null },
  },
  {
    name: "Payment Gateway",
    description: "Card validation \u2192 processing \u2192 3DS \u2192 result",
    icon: <CreditCard className="w-5 h-5" />,
    color: "#6366f1",
    category: "E-Commerce",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "validating", type: "atomic" },
      { id: "processing", type: "atomic" },
      { id: "three_ds", type: "atomic" },
      { id: "approved", type: "final" },
      { id: "declined", type: "final" },
    ],
    transitions: [
      { source: "idle", target: "validating", event: "SUBMIT" },
      { source: "validating", target: "processing", event: "VALID" },
      { source: "validating", target: "declined", event: "INVALID" },
      { source: "processing", target: "three_ds", event: "REQUIRES_3DS" },
      { source: "processing", target: "approved", event: "SUCCESS" },
      { source: "processing", target: "declined", event: "DECLINE" },
      { source: "three_ds", target: "approved", event: "VERIFIED" },
      { source: "three_ds", target: "declined", event: "FAILED" },
    ],
    context: { amount: 0, currency: "USD" },
  },
];

export const IOT_HARDWARE_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Smart Thermostat",
    description: "Idle \u2194 heating \u2194 cooling with temperature guards",
    icon: <Thermometer className="w-5 h-5" />,
    color: "#f43f5e",
    category: "IoT & Hardware",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "heating", type: "atomic" },
      { id: "cooling", type: "atomic" },
      { id: "eco_mode", type: "atomic" },
    ],
    transitions: [
      { source: "idle", target: "heating", event: "TEMP_LOW" },
      { source: "idle", target: "cooling", event: "TEMP_HIGH" },
      { source: "heating", target: "idle", event: "TEMP_OK" },
      { source: "cooling", target: "idle", event: "TEMP_OK" },
      { source: "idle", target: "eco_mode", event: "ECO_ON" },
      { source: "eco_mode", target: "idle", event: "ECO_OFF" },
    ],
    context: { currentTemp: 22, targetTemp: 22 },
  },
  {
    name: "IoT Device Lifecycle",
    description: "Provisioning \u2192 online \u2192 firmware update \u2192 offline",
    icon: <Wifi className="w-5 h-5" />,
    color: "#0ea5e9",
    category: "IoT & Hardware",
    initialState: "unprovisioned",
    states: [
      { id: "unprovisioned", type: "atomic" },
      { id: "provisioning", type: "atomic" },
      { id: "online", type: "atomic" },
      { id: "updating", type: "atomic" },
      { id: "offline", type: "atomic" },
      { id: "error", type: "atomic" },
    ],
    transitions: [
      { source: "unprovisioned", target: "provisioning", event: "PROVISION" },
      { source: "provisioning", target: "online", event: "SUCCESS" },
      { source: "provisioning", target: "error", event: "FAILURE" },
      { source: "online", target: "updating", event: "OTA_UPDATE" },
      { source: "updating", target: "online", event: "UPDATE_DONE" },
      { source: "updating", target: "error", event: "UPDATE_FAIL" },
      { source: "online", target: "offline", event: "DISCONNECT" },
      { source: "offline", target: "online", event: "RECONNECT" },
      { source: "error", target: "provisioning", event: "RETRY" },
    ],
    context: { firmwareVersion: "1.0.0", deviceId: null },
  },
  {
    name: "Sensor Pipeline",
    description: "Sensor data: sample \u2192 validate \u2192 process \u2192 store",
    icon: <Activity className="w-5 h-5" />,
    color: "#14b8a6",
    category: "IoT & Hardware",
    initialState: "sampling",
    states: [
      { id: "sampling", type: "atomic" },
      { id: "validating", type: "atomic" },
      { id: "processing", type: "atomic" },
      { id: "storing", type: "atomic" },
      { id: "alerting", type: "atomic" },
    ],
    transitions: [
      { source: "sampling", target: "validating", event: "DATA_READY" },
      { source: "validating", target: "processing", event: "VALID" },
      { source: "validating", target: "sampling", event: "INVALID" },
      { source: "processing", target: "storing", event: "PROCESSED" },
      { source: "processing", target: "alerting", event: "ANOMALY" },
      { source: "storing", target: "sampling", event: "STORED" },
      { source: "alerting", target: "sampling", event: "ACKNOWLEDGED" },
    ],
    context: { sampleRate: 1000, threshold: 100 },
  },
];

export const GAMING_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Game Character",
    description: "Idle \u2192 walk \u2192 run \u2192 jump \u2192 attack states",
    icon: <Gamepad2 className="w-5 h-5" />,
    color: "#ec4899",
    category: "Gaming",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "walking", type: "atomic" },
      { id: "running", type: "atomic" },
      { id: "jumping", type: "atomic" },
      { id: "attacking", type: "atomic" },
      { id: "dead", type: "final" },
    ],
    transitions: [
      { source: "idle", target: "walking", event: "MOVE" },
      { source: "walking", target: "running", event: "SPRINT" },
      { source: "running", target: "walking", event: "SLOW_DOWN" },
      { source: "walking", target: "idle", event: "STOP" },
      { source: "running", target: "idle", event: "STOP" },
      { source: "idle", target: "jumping", event: "JUMP" },
      { source: "walking", target: "jumping", event: "JUMP" },
      { source: "jumping", target: "idle", event: "LAND" },
      { source: "idle", target: "attacking", event: "ATTACK" },
      { source: "attacking", target: "idle", event: "ATTACK_END" },
      { source: "idle", target: "dead", event: "DIE" },
      { source: "walking", target: "dead", event: "DIE" },
    ],
    context: { hp: 100, stamina: 100, position: 0 },
  },
  {
    name: "Turn-Based Combat",
    description: "Player turn \u2192 enemy turn \u2192 victory/defeat",
    icon: <Layers className="w-5 h-5" />,
    color: "#dc2626",
    category: "Gaming",
    initialState: "player_turn",
    states: [
      { id: "player_turn", type: "atomic" },
      { id: "player_action", type: "atomic" },
      { id: "enemy_turn", type: "atomic" },
      { id: "enemy_action", type: "atomic" },
      { id: "victory", type: "final" },
      { id: "defeat", type: "final" },
    ],
    transitions: [
      {
        source: "player_turn",
        target: "player_action",
        event: "CHOOSE_ACTION",
      },
      { source: "player_action", target: "enemy_turn", event: "ACTION_DONE" },
      { source: "player_action", target: "victory", event: "ENEMY_DEAD" },
      { source: "enemy_turn", target: "enemy_action", event: "AI_DECIDE" },
      { source: "enemy_action", target: "player_turn", event: "ACTION_DONE" },
      { source: "enemy_action", target: "defeat", event: "PLAYER_DEAD" },
    ],
    context: { playerHp: 100, enemyHp: 50, turn: 1 },
  },
  {
    name: "Match Lobby",
    description: "Matchmaking queue \u2192 lobby \u2192 countdown \u2192 playing",
    icon: <Gamepad2 className="w-5 h-5" />,
    color: "#a3e635",
    category: "Gaming",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "queuing", type: "atomic" },
      { id: "lobby", type: "atomic" },
      { id: "countdown", type: "atomic" },
      { id: "playing", type: "atomic" },
      { id: "results", type: "final" },
    ],
    transitions: [
      { source: "idle", target: "queuing", event: "FIND_MATCH" },
      { source: "queuing", target: "lobby", event: "MATCH_FOUND" },
      { source: "queuing", target: "idle", event: "CANCEL" },
      { source: "lobby", target: "countdown", event: "ALL_READY" },
      { source: "lobby", target: "idle", event: "LEAVE" },
      { source: "countdown", target: "playing", event: "GO" },
      { source: "playing", target: "results", event: "GAME_OVER" },
    ],
    context: { players: 0, maxPlayers: 10 },
  },
];
