/**
 * State Machine Templates: DevOps & CI/CD, Healthcare, Communication
 */

import {
  Cloud,
  Cog,
  Database,
  FileText,
  HeartPulse,
  MessageSquare,
  Phone,
  Send,
} from "lucide-react";
import type { TemplateDefinition } from "../TemplateLibrary";

export const DEVOPS_TEMPLATES: TemplateDefinition[] = [
  {
    name: "CI/CD Pipeline",
    description: "Build \u2192 test \u2192 stage \u2192 deploy \u2192 rollback",
    icon: <Cog className="w-5 h-5" />,
    color: "#f97316",
    category: "DevOps & CI/CD",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "building", type: "atomic" },
      { id: "testing", type: "atomic" },
      { id: "staging", type: "atomic" },
      { id: "deploying", type: "atomic" },
      { id: "live", type: "atomic" },
      { id: "rolling_back", type: "atomic" },
      { id: "failed", type: "atomic" },
    ],
    transitions: [
      { source: "idle", target: "building", event: "PUSH" },
      { source: "building", target: "testing", event: "BUILD_OK" },
      { source: "building", target: "failed", event: "BUILD_FAIL" },
      { source: "testing", target: "staging", event: "TESTS_PASS" },
      { source: "testing", target: "failed", event: "TESTS_FAIL" },
      { source: "staging", target: "deploying", event: "APPROVE" },
      { source: "staging", target: "idle", event: "REJECT" },
      { source: "deploying", target: "live", event: "DEPLOY_OK" },
      { source: "deploying", target: "rolling_back", event: "DEPLOY_FAIL" },
      { source: "rolling_back", target: "idle", event: "ROLLBACK_DONE" },
      { source: "live", target: "rolling_back", event: "ROLLBACK" },
      { source: "failed", target: "idle", event: "RESET" },
    ],
    context: { commitHash: null, version: "0.0.0" },
  },
  {
    name: "Container Lifecycle",
    description: "Docker container: create \u2192 start \u2192 stop \u2192 remove",
    icon: <Database className="w-5 h-5" />,
    color: "#2563eb",
    category: "DevOps & CI/CD",
    initialState: "created",
    states: [
      { id: "created", type: "atomic" },
      { id: "running", type: "atomic" },
      { id: "paused", type: "atomic" },
      { id: "stopped", type: "atomic" },
      { id: "removed", type: "final" },
    ],
    transitions: [
      { source: "created", target: "running", event: "START" },
      { source: "running", target: "paused", event: "PAUSE" },
      { source: "paused", target: "running", event: "UNPAUSE" },
      { source: "running", target: "stopped", event: "STOP" },
      { source: "paused", target: "stopped", event: "STOP" },
      { source: "stopped", target: "running", event: "RESTART" },
      { source: "stopped", target: "removed", event: "REMOVE" },
    ],
    context: { containerId: null, image: "" },
  },
  {
    name: "Incident Response",
    description: "Alert detected \u2192 triage \u2192 mitigate \u2192 resolve \u2192 postmortem",
    icon: <Cloud className="w-5 h-5" />,
    color: "#ef4444",
    category: "DevOps & CI/CD",
    initialState: "normal",
    states: [
      { id: "normal", type: "atomic" },
      { id: "alert", type: "atomic" },
      { id: "triage", type: "atomic" },
      { id: "mitigating", type: "atomic" },
      { id: "resolved", type: "atomic" },
      { id: "postmortem", type: "final" },
    ],
    transitions: [
      { source: "normal", target: "alert", event: "ALERT_FIRED" },
      { source: "alert", target: "triage", event: "ACKNOWLEDGE" },
      { source: "alert", target: "normal", event: "FALSE_ALARM" },
      { source: "triage", target: "mitigating", event: "ESCALATE" },
      { source: "mitigating", target: "resolved", event: "FIX_APPLIED" },
      { source: "resolved", target: "postmortem", event: "CLOSE" },
      { source: "resolved", target: "mitigating", event: "REGRESSION" },
    ],
    context: { severity: "medium", assignee: null },
  },
];

export const HEALTHCARE_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Patient Visit",
    description: "Check-in \u2192 triage \u2192 exam \u2192 diagnosis \u2192 discharge",
    icon: <HeartPulse className="w-5 h-5" />,
    color: "#ef4444",
    category: "Healthcare",
    initialState: "registered",
    states: [
      { id: "registered", type: "atomic" },
      { id: "checked_in", type: "atomic" },
      { id: "triage", type: "atomic" },
      { id: "waiting", type: "atomic" },
      { id: "examination", type: "atomic" },
      { id: "treatment", type: "atomic" },
      { id: "discharged", type: "final" },
    ],
    transitions: [
      { source: "registered", target: "checked_in", event: "CHECK_IN" },
      { source: "checked_in", target: "triage", event: "TRIAGE" },
      { source: "triage", target: "waiting", event: "ASSESSED" },
      { source: "waiting", target: "examination", event: "CALLED" },
      { source: "examination", target: "treatment", event: "DIAGNOSED" },
      { source: "treatment", target: "discharged", event: "DISCHARGE" },
      { source: "examination", target: "discharged", event: "ALL_CLEAR" },
    ],
    context: { patientId: null, priority: "normal" },
  },
  {
    name: "Prescription Workflow",
    description: "Written \u2192 verified \u2192 dispensed \u2192 collected",
    icon: <FileText className="w-5 h-5" />,
    color: "#16a34a",
    category: "Healthcare",
    initialState: "written",
    states: [
      { id: "written", type: "atomic" },
      { id: "verified", type: "atomic" },
      { id: "dispensing", type: "atomic" },
      { id: "ready", type: "atomic" },
      { id: "collected", type: "final" },
      { id: "rejected", type: "final" },
    ],
    transitions: [
      { source: "written", target: "verified", event: "VERIFY" },
      { source: "written", target: "rejected", event: "REJECT" },
      { source: "verified", target: "dispensing", event: "DISPENSE" },
      { source: "dispensing", target: "ready", event: "PACKED" },
      { source: "ready", target: "collected", event: "PICKUP" },
    ],
    context: { drugName: "", dosage: "", pharmacist: null },
  },
];

export const COMMUNICATION_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Phone Call",
    description: "Dialing \u2192 ringing \u2192 connected \u2192 hangup",
    icon: <Phone className="w-5 h-5" />,
    color: "#22c55e",
    category: "Communication",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "dialing", type: "atomic" },
      { id: "ringing", type: "atomic" },
      { id: "connected", type: "atomic" },
      { id: "on_hold", type: "atomic" },
      { id: "ended", type: "final" },
    ],
    transitions: [
      { source: "idle", target: "dialing", event: "DIAL" },
      { source: "dialing", target: "ringing", event: "RING" },
      { source: "dialing", target: "ended", event: "BUSY" },
      { source: "ringing", target: "connected", event: "ANSWER" },
      { source: "ringing", target: "ended", event: "NO_ANSWER" },
      { source: "connected", target: "on_hold", event: "HOLD" },
      { source: "on_hold", target: "connected", event: "RESUME" },
      { source: "connected", target: "ended", event: "HANGUP" },
      { source: "on_hold", target: "ended", event: "HANGUP" },
    ],
    context: { caller: null, callee: null, duration: 0 },
  },
  {
    name: "Chat Message",
    description: "Draft \u2192 sending \u2192 delivered \u2192 read lifecycle",
    icon: <MessageSquare className="w-5 h-5" />,
    color: "#8b5cf6",
    category: "Communication",
    initialState: "draft",
    states: [
      { id: "draft", type: "atomic" },
      { id: "sending", type: "atomic" },
      { id: "sent", type: "atomic" },
      { id: "delivered", type: "atomic" },
      { id: "read", type: "final" },
      { id: "failed", type: "atomic" },
    ],
    transitions: [
      { source: "draft", target: "sending", event: "SEND" },
      { source: "sending", target: "sent", event: "ACK" },
      { source: "sending", target: "failed", event: "TIMEOUT" },
      { source: "sent", target: "delivered", event: "DELIVERED" },
      { source: "delivered", target: "read", event: "READ" },
      { source: "failed", target: "sending", event: "RETRY" },
    ],
    context: { messageId: null, timestamp: null },
  },
  {
    name: "Email Campaign",
    description: "Draft \u2192 scheduled \u2192 sending \u2192 analyzing results",
    icon: <Send className="w-5 h-5" />,
    color: "#0891b2",
    category: "Communication",
    initialState: "draft",
    states: [
      { id: "draft", type: "atomic" },
      { id: "review", type: "atomic" },
      { id: "scheduled", type: "atomic" },
      { id: "sending", type: "atomic" },
      { id: "sent", type: "atomic" },
      { id: "analyzing", type: "final" },
    ],
    transitions: [
      { source: "draft", target: "review", event: "SUBMIT" },
      { source: "review", target: "draft", event: "REVISE" },
      { source: "review", target: "scheduled", event: "APPROVE" },
      { source: "scheduled", target: "sending", event: "TRIGGER" },
      { source: "scheduled", target: "draft", event: "CANCEL" },
      { source: "sending", target: "sent", event: "ALL_SENT" },
      { source: "sent", target: "analyzing", event: "ANALYZE" },
    ],
    context: { recipients: 0, openRate: 0, subject: "" },
  },
];
