/**
 * State Machine Templates: Workflow, Finance, Embedded
 */

import {
  BookOpen,
  Building2,
  Coffee,
  Cog,
  Cpu,
  CreditCard,
  FileText,
  ListOrdered,
  Ticket,
  Workflow,
} from "lucide-react";
import type { TemplateDefinition } from "../TemplateLibrary";

export const WORKFLOW_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Form Wizard",
    description: "Multi-step form with NEXT/BACK navigation",
    icon: <ListOrdered className="w-5 h-5" />,
    color: "#8b5cf6",
    category: "Workflow",
    initialState: "step1",
    states: [
      { id: "step1", type: "atomic" },
      { id: "step2", type: "atomic" },
      { id: "step3", type: "atomic" },
      { id: "submitted", type: "final" },
    ],
    transitions: [
      { source: "step1", target: "step2", event: "NEXT" },
      { source: "step2", target: "step3", event: "NEXT" },
      { source: "step2", target: "step1", event: "BACK" },
      { source: "step3", target: "step2", event: "BACK" },
      { source: "step3", target: "submitted", event: "SUBMIT" },
    ],
    context: { formData: {} },
  },
  {
    name: "Document Approval",
    description: "Draft \u2192 review \u2192 approved/rejected lifecycle",
    icon: <FileText className="w-5 h-5" />,
    color: "#0d9488",
    category: "Workflow",
    initialState: "draft",
    states: [
      { id: "draft", type: "atomic" },
      { id: "submitted", type: "atomic" },
      { id: "reviewing", type: "atomic" },
      { id: "changes_requested", type: "atomic" },
      { id: "approved", type: "final" },
      { id: "rejected", type: "final" },
    ],
    transitions: [
      { source: "draft", target: "submitted", event: "SUBMIT" },
      { source: "submitted", target: "reviewing", event: "ASSIGN_REVIEWER" },
      { source: "reviewing", target: "approved", event: "APPROVE" },
      { source: "reviewing", target: "rejected", event: "REJECT" },
      {
        source: "reviewing",
        target: "changes_requested",
        event: "REQUEST_CHANGES",
      },
      { source: "changes_requested", target: "draft", event: "REVISE" },
    ],
    context: { documentId: null, reviewer: null, version: 1 },
  },
  {
    name: "Support Ticket",
    description: "Open \u2192 assigned \u2192 investigation \u2192 resolved \u2192 closed",
    icon: <Ticket className="w-5 h-5" />,
    color: "#d946ef",
    category: "Workflow",
    initialState: "open",
    states: [
      { id: "open", type: "atomic" },
      { id: "assigned", type: "atomic" },
      { id: "investigating", type: "atomic" },
      { id: "waiting_customer", type: "atomic" },
      { id: "resolved", type: "atomic" },
      { id: "closed", type: "final" },
      { id: "reopened", type: "atomic" },
    ],
    transitions: [
      { source: "open", target: "assigned", event: "ASSIGN" },
      { source: "assigned", target: "investigating", event: "START_WORK" },
      {
        source: "investigating",
        target: "waiting_customer",
        event: "NEED_INFO",
      },
      {
        source: "waiting_customer",
        target: "investigating",
        event: "CUSTOMER_REPLY",
      },
      { source: "investigating", target: "resolved", event: "RESOLVE" },
      { source: "resolved", target: "closed", event: "CLOSE" },
      { source: "resolved", target: "reopened", event: "REOPEN" },
      { source: "reopened", target: "investigating", event: "ASSIGN" },
    ],
    context: { priority: "medium", assignee: null, sla: 24 },
  },
  {
    name: "Kanban Board",
    description: "Backlog \u2192 todo \u2192 in progress \u2192 review \u2192 done",
    icon: <Workflow className="w-5 h-5" />,
    color: "#3b82f6",
    category: "Workflow",
    initialState: "backlog",
    states: [
      { id: "backlog", type: "atomic" },
      { id: "todo", type: "atomic" },
      { id: "in_progress", type: "atomic" },
      { id: "in_review", type: "atomic" },
      { id: "done", type: "final" },
      { id: "blocked", type: "atomic" },
    ],
    transitions: [
      { source: "backlog", target: "todo", event: "PRIORITIZE" },
      { source: "todo", target: "in_progress", event: "START" },
      { source: "in_progress", target: "in_review", event: "SUBMIT" },
      { source: "in_progress", target: "blocked", event: "BLOCK" },
      { source: "blocked", target: "in_progress", event: "UNBLOCK" },
      { source: "in_review", target: "done", event: "APPROVE" },
      { source: "in_review", target: "in_progress", event: "CHANGES_NEEDED" },
    ],
    context: { assignee: null, storyPoints: 0 },
  },
  {
    name: "Course Enrollment",
    description: "Browse \u2192 enroll \u2192 learning \u2192 exam \u2192 certificate",
    icon: <BookOpen className="w-5 h-5" />,
    color: "#7c3aed",
    category: "Workflow",
    initialState: "browsing",
    states: [
      { id: "browsing", type: "atomic" },
      { id: "enrolled", type: "atomic" },
      { id: "learning", type: "atomic" },
      { id: "exam", type: "atomic" },
      { id: "passed", type: "final" },
      { id: "failed_exam", type: "atomic" },
      { id: "dropped", type: "final" },
    ],
    transitions: [
      { source: "browsing", target: "enrolled", event: "ENROLL" },
      { source: "enrolled", target: "learning", event: "START_COURSE" },
      { source: "enrolled", target: "dropped", event: "DROP" },
      { source: "learning", target: "exam", event: "TAKE_EXAM" },
      { source: "exam", target: "passed", event: "PASS" },
      { source: "exam", target: "failed_exam", event: "FAIL" },
      { source: "failed_exam", target: "exam", event: "RETAKE" },
      { source: "failed_exam", target: "dropped", event: "DROP" },
    ],
    context: { courseId: null, progress: 0, attempts: 0 },
  },
];

export const FINANCE_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Loan Application",
    description: "Application \u2192 credit check \u2192 approval \u2192 disbursement",
    icon: <Building2 className="w-5 h-5" />,
    color: "#059669",
    category: "Finance",
    initialState: "submitted",
    states: [
      { id: "submitted", type: "atomic" },
      { id: "credit_check", type: "atomic" },
      { id: "underwriting", type: "atomic" },
      { id: "approved", type: "atomic" },
      { id: "disbursed", type: "final" },
      { id: "rejected", type: "final" },
    ],
    transitions: [
      { source: "submitted", target: "credit_check", event: "PROCESS" },
      { source: "credit_check", target: "underwriting", event: "SCORE_OK" },
      { source: "credit_check", target: "rejected", event: "SCORE_LOW" },
      { source: "underwriting", target: "approved", event: "APPROVE" },
      { source: "underwriting", target: "rejected", event: "DENY" },
      { source: "approved", target: "disbursed", event: "DISBURSE" },
    ],
    context: { amount: 0, creditScore: 0, interestRate: 0 },
  },
  {
    name: "Invoice Lifecycle",
    description: "Created \u2192 sent \u2192 partial/paid \u2192 overdue \u2192 collected",
    icon: <CreditCard className="w-5 h-5" />,
    color: "#ca8a04",
    category: "Finance",
    initialState: "created",
    states: [
      { id: "created", type: "atomic" },
      { id: "sent", type: "atomic" },
      { id: "partial_paid", type: "atomic" },
      { id: "paid", type: "final" },
      { id: "overdue", type: "atomic" },
      { id: "written_off", type: "final" },
    ],
    transitions: [
      { source: "created", target: "sent", event: "SEND" },
      { source: "sent", target: "partial_paid", event: "PARTIAL_PAYMENT" },
      { source: "sent", target: "paid", event: "FULL_PAYMENT" },
      { source: "partial_paid", target: "paid", event: "FULL_PAYMENT" },
      { source: "sent", target: "overdue", event: "DUE_DATE_PASSED" },
      { source: "partial_paid", target: "overdue", event: "DUE_DATE_PASSED" },
      { source: "overdue", target: "paid", event: "FULL_PAYMENT" },
      { source: "overdue", target: "written_off", event: "WRITE_OFF" },
    ],
    context: { amount: 0, paid: 0, dueDate: null },
  },
];

export const EMBEDDED_TEMPLATES: TemplateDefinition[] = [
  {
    name: "Elevator Controller",
    description: "Idle \u2192 moving up/down \u2192 door open/close at each floor",
    icon: <Cpu className="w-5 h-5" />,
    color: "#6d28d9",
    category: "Embedded",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "moving_up", type: "atomic" },
      { id: "moving_down", type: "atomic" },
      { id: "door_opening", type: "atomic" },
      { id: "door_open", type: "atomic" },
      { id: "door_closing", type: "atomic" },
      { id: "emergency", type: "atomic" },
    ],
    transitions: [
      { source: "idle", target: "moving_up", event: "CALL_UP" },
      { source: "idle", target: "moving_down", event: "CALL_DOWN" },
      { source: "moving_up", target: "door_opening", event: "ARRIVED" },
      { source: "moving_down", target: "door_opening", event: "ARRIVED" },
      { source: "door_opening", target: "door_open", event: "OPENED" },
      { source: "door_open", target: "door_closing", event: "TIMER" },
      { source: "door_closing", target: "idle", event: "CLOSED" },
      { source: "door_closing", target: "door_opening", event: "OBSTRUCTION" },
      { source: "moving_up", target: "emergency", event: "EMERGENCY" },
      { source: "moving_down", target: "emergency", event: "EMERGENCY" },
      { source: "emergency", target: "idle", event: "RESET" },
    ],
    context: { currentFloor: 1, targetFloor: 1 },
  },
  {
    name: "Vending Machine",
    description: "Insert coin \u2192 select \u2192 dispense \u2192 change cycle",
    icon: <Coffee className="w-5 h-5" />,
    color: "#b45309",
    category: "Embedded",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "accepting_coins", type: "atomic" },
      { id: "selecting", type: "atomic" },
      { id: "dispensing", type: "atomic" },
      { id: "returning_change", type: "atomic" },
    ],
    transitions: [
      { source: "idle", target: "accepting_coins", event: "INSERT_COIN" },
      {
        source: "accepting_coins",
        target: "accepting_coins",
        event: "INSERT_COIN",
      },
      {
        source: "accepting_coins",
        target: "selecting",
        event: "ENOUGH_CREDIT",
      },
      {
        source: "accepting_coins",
        target: "returning_change",
        event: "CANCEL",
      },
      { source: "selecting", target: "dispensing", event: "SELECT" },
      { source: "dispensing", target: "returning_change", event: "DISPENSED" },
      { source: "returning_change", target: "idle", event: "DONE" },
    ],
    context: { credit: 0, selectedItem: null },
  },
  {
    name: "Washing Machine",
    description: "Load \u2192 wash \u2192 rinse \u2192 spin \u2192 done cycle",
    icon: <Cog className="w-5 h-5" />,
    color: "#0284c7",
    category: "Embedded",
    initialState: "idle",
    states: [
      { id: "idle", type: "atomic" },
      { id: "filling", type: "atomic" },
      { id: "washing", type: "atomic" },
      { id: "rinsing", type: "atomic" },
      { id: "spinning", type: "atomic" },
      { id: "done", type: "atomic" },
      { id: "error", type: "atomic" },
    ],
    transitions: [
      { source: "idle", target: "filling", event: "START" },
      { source: "filling", target: "washing", event: "FULL" },
      { source: "filling", target: "error", event: "WATER_FAULT" },
      { source: "washing", target: "rinsing", event: "WASH_DONE" },
      { source: "rinsing", target: "spinning", event: "RINSE_DONE" },
      { source: "spinning", target: "done", event: "SPIN_DONE" },
      { source: "done", target: "idle", event: "OPEN_DOOR" },
      { source: "error", target: "idle", event: "RESET" },
    ],
    context: { program: "normal", temperature: 40 },
  },
];
