// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

 
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  codeSpace: __t.string().primaryKey().name("code_space"),
  code: __t.string(),
  html: __t.string(),
  css: __t.string(),
  transpiled: __t.string(),
  messagesJson: __t.string().name("messages_json"),
  lastUpdatedBy: __t.identity().name("last_updated_by"),
  updatedAt: __t.u64().name("updated_at"),
});
