// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

 
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fromIdentity: __t.identity().name("from_identity"),
  toIdentity: __t.identity().name("to_identity"),
  content: __t.string(),
  readStatus: __t.bool().name("read_status"),
  createdAt: __t.u64().name("created_at"),
});
