// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

 
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  toolName: __t.string().name("tool_name"),
  argumentsJson: __t.string().name("arguments_json"),
  requesterIdentity: __t.identity().name("requester_identity"),
  providerIdentity: __t.option(__t.identity()).name("provider_identity"),
  status: __t.string(),
  resultJson: __t.option(__t.string()).name("result_json"),
  error: __t.option(__t.string()),
  createdAt: __t.u64().name("created_at"),
  completedAt: __t.option(__t.u64()).name("completed_at"),
});
