/**
 * /create App Generator MCP Tools
 *
 * Search, classify, and manage AI-generated React apps from the /create feature.
 */

import { z } from "zod";
import type { ToolRegistry } from "../tool-registry";
import { textResult } from "./tool-helpers";
import { freeTool } from "../tool-builder/procedures";

export function registerCreateTools(
    registry: ToolRegistry,
    _userId: string,
): void {
    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_search_apps", "Search published /create apps by title, description, or slug. "
                + "Results are ordered by popularity (view count).", {
                query: z.string().min(1).describe(
                    "Search query to match against app title, description, or slug.",
                ),
                limit: z.number().int().min(1).max(50).optional().describe(
                    "Max results (default 10).",
                ),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, ctx }) => {
                const {
                    query,
                    limit = 10,
                } = input;

                const apps = await ctx.prisma.createdApp.findMany({
                    where: {
                        status: "PUBLISHED",
                        OR: [
                            { title: { contains: query, mode: "insensitive" } },
                            { description: { contains: query, mode: "insensitive" } },
                            { slug: { contains: query, mode: "insensitive" } },
                        ],
                    },
                    select: {
                        slug: true,
                        title: true,
                        description: true,
                        codespaceUrl: true,
                        viewCount: true,
                        generatedAt: true,
                    },
                    orderBy: { viewCount: "desc" },
                    take: limit,
                });

                if (apps.length === 0) {
                    return textResult(`No apps found matching "${query}".`);
                }

                let text = `**Found ${apps.length} app(s) matching "${query}":**\n\n`;
                for (const app of apps) {
                    text += `- **${app.title}** (\`${app.slug}\`)\n`;
                    text += `  ${app.description.slice(0, 150)}\n`;
                    text += `  Views: ${app.viewCount} | URL: ${app.codespaceUrl}\n\n`;
                }

                return textResult(text);
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_get_app", "Get full details for a specific /create app by its slug, "
                + "including the prompt used to generate it.", {
                slug: z.string().min(1).describe("Unique slug of the created app."),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, ctx }) => {
                const {
                    slug,
                } = input;

                const app = await ctx.prisma.createdApp.findUnique({
                    where: { slug },
                    include: {
                        generatedBy: {
                            select: { id: true, name: true },
                        },
                    },
                });

                if (!app) {
                    return textResult(
                        `**Error: NOT_FOUND**\nNo app found with slug "${slug}".\n**Retryable:** false`,
                    );
                }

                let text = `**${app.title}**\n\n`;
                text += `**Slug:** ${app.slug}\n`;
                text += `**Status:** ${app.status}\n`;
                text += `**Description:** ${app.description}\n`;
                text += `**Codespace ID:** ${app.codespaceId}\n`;
                text += `**Codespace URL:** ${app.codespaceUrl}\n`;
                text += `**Views:** ${app.viewCount}\n`;
                text += `**Generated:** ${app.generatedAt.toISOString()}\n`;
                if (app.generatedBy) {
                    text += `**Generated By:** ${app.generatedBy.name || app.generatedBy.id}\n`;
                }
                text += `**Prompt Used:** ${app.promptUsed.slice(0, 500)}\n`;
                if (app.outgoingLinks.length > 0) {
                    text += `**Links:** ${app.outgoingLinks.join(", ")}\n`;
                }

                return textResult(text);
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_classify_idea", "Classify an app idea into a URL slug and category using AI. "
                + "Returns status (ok/blocked/unclear), slug, category, and reason.", {
                text: z.string().min(1).max(2000).describe(
                    "App idea text to classify into a slug and category.",
                ),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, _ctx }) => {
                const {
                    text,
                } = input;

                const { classifyInput } = await import("@/lib/create/slug-classifier");

                const result = await classifyInput(text);

                let output = `**Classification Result**\n\n`;
                output += `**Status:** ${result.status}\n`;
                output += `**Slug:** ${result.slug || "(none)"}\n`;
                output += `**Category:** ${result.category || "(none)"}\n`;
                if (result.reason) {
                    output += `**Reason:** ${result.reason}\n`;
                }

                return textResult(output);
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_check_health", "Check if a codespace is healthy (has real, non-default content). "
                + "Returns true/false.", {
                codespace_id: z.string().min(1).describe("Codespace ID to check health for."),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, _ctx }) => {
                const {
                    codespace_id,
                } = input;

                const { isCodespaceHealthy } = await import(
                    "@/lib/create/codespace-health"
                );

                const healthy = await isCodespaceHealthy(codespace_id);

                return textResult(
                    `**Codespace Health Check**\n\n`
                    + `**ID:** ${codespace_id}\n`
                    + `**Healthy:** ${healthy}`,
                );
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_list_top_apps", "List the most popular published /create apps by view count. "
                + "Only healthy codespaces are included.", {
                limit: z.number().int().min(1).max(50).optional().describe(
                    "Max results (default 10).",
                ),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, ctx }) => {
                const {
                    limit = 10,
                } = input;
                const { filterHealthyCodespaces } = await import(
                    "@/lib/create/codespace-health"
                );

                // Fetch more than needed to account for unhealthy ones being filtered out
                const apps = await ctx.prisma.createdApp.findMany({
                    where: { status: "PUBLISHED" },
                    select: {
                        slug: true,
                        title: true,
                        description: true,
                        codespaceId: true,
                        codespaceUrl: true,
                        viewCount: true,
                    },
                    orderBy: { viewCount: "desc" },
                    take: limit * 2,
                });

                const healthy = await filterHealthyCodespaces(apps);
                const result = healthy.slice(0, limit);

                if (result.length === 0) {
                    return textResult("No healthy published apps found.");
                }

                let text = `**Top ${result.length} App(s) by Views:**\n\n`;
                for (const app of result) {
                    text += `- **${app.title}** (\`${app.slug}\`) — ${app.viewCount} views\n`;
                    text += `  ${app.description.slice(0, 120)}\n`;
                    text += `  URL: ${app.codespaceUrl}\n\n`;
                }

                return textResult(text);
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_list_recent_apps", "List the most recently generated published /create apps. "
                + "Only healthy codespaces are included.", {
                limit: z.number().int().min(1).max(50).optional().describe(
                    "Max results (default 10).",
                ),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, ctx }) => {
                const {
                    limit = 10,
                } = input;
                const { filterHealthyCodespaces } = await import(
                    "@/lib/create/codespace-health"
                );

                const apps = await ctx.prisma.createdApp.findMany({
                    where: { status: "PUBLISHED" },
                    select: {
                        slug: true,
                        title: true,
                        description: true,
                        codespaceId: true,
                        codespaceUrl: true,
                        viewCount: true,
                        generatedAt: true,
                    },
                    orderBy: { generatedAt: "desc" },
                    take: limit * 2,
                });

                const healthy = await filterHealthyCodespaces(apps);
                const result = healthy.slice(0, limit);

                if (result.length === 0) {
                    return textResult("No healthy recent apps found.");
                }

                let text = `**${result.length} Most Recent App(s):**\n\n`;
                for (const app of result) {
                    text += `- **${app.title}** (\`${app.slug}\`)\n`;
                    text += `  ${app.description.slice(0, 120)}\n`;
                    text += `  Generated: ${app.generatedAt!.toISOString()} | Views: ${app.viewCount}\n`;
                    text += `  URL: ${app.codespaceUrl}\n\n`;
                }

                return textResult(text);
            })
    );

    registry.registerBuilt(
        freeTool(_userId)
            .tool("create_get_app_status", "Quick status check for a /create app. "
                + "Returns GENERATING, PUBLISHED, or FAILED with the codespace URL.", {
                slug: z.string().min(1).describe("Unique slug of the created app."),
            })
            .meta({ category: "create", tier: "free" })
            .handler(async ({ input, ctx }) => {
                const {
                    slug,
                } = input;

                const app = await ctx.prisma.createdApp.findUnique({
                    where: { slug },
                    select: {
                        slug: true,
                        title: true,
                        status: true,
                        codespaceUrl: true,
                    },
                });

                if (!app) {
                    return textResult(
                        `**Error: NOT_FOUND**\nNo app found with slug "${slug}".\n**Retryable:** false`,
                    );
                }

                return textResult(
                    `**App Status**\n\n`
                    + `**Title:** ${app.title}\n`
                    + `**Slug:** ${app.slug}\n`
                    + `**Status:** ${app.status}\n`
                    + `**URL:** ${app.codespaceUrl}`,
                );
            })
    );
}
