// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimMcpTaskReducer from "../claim_mcp_task_reducer";
import CompleteMcpTaskReducer from "../complete_mcp_task_reducer";
import CreateAppReducer from "../create_app_reducer";
import CreateAppVersionReducer from "../create_app_version_reducer";
import CreatePageReducer from "../create_page_reducer";
import CreatePageBlockReducer from "../create_page_block_reducer";
import DeleteAppReducer from "../delete_app_reducer";
import DeletePageReducer from "../delete_page_reducer";
import DeletePageBlockReducer from "../delete_page_block_reducer";
import InvokeToolRequestReducer from "../invoke_tool_request_reducer";
import LinkOauthReducer from "../link_oauth_reducer";
import MarkAgentMessageDeliveredReducer from "../mark_agent_message_delivered_reducer";
import MarkDmReadReducer from "../mark_dm_read_reducer";
import RecordHealthCheckReducer from "../record_health_check_reducer";
import RecordPlatformEventReducer from "../record_platform_event_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RegisterToolReducer from "../register_tool_reducer";
import RegisterUserReducer from "../register_user_reducer";
import ReorderPageBlocksReducer from "../reorder_page_blocks_reducer";
import RestoreAppReducer from "../restore_app_reducer";
import SendAgentMessageReducer from "../send_agent_message_reducer";
import SendAppMessageReducer from "../send_app_message_reducer";
import SendDmReducer from "../send_dm_reducer";
import UnregisterAgentReducer from "../unregister_agent_reducer";
import UnregisterToolReducer from "../unregister_tool_reducer";
import UpdateAppReducer from "../update_app_reducer";
import UpdateAppStatusReducer from "../update_app_status_reducer";
import UpdateCodeSessionReducer from "../update_code_session_reducer";
import UpdatePageReducer from "../update_page_reducer";
import UpdatePageBlockReducer from "../update_page_block_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type ClaimMcpTaskParams = __Infer<typeof ClaimMcpTaskReducer>;
export type CompleteMcpTaskParams = __Infer<typeof CompleteMcpTaskReducer>;
export type CreateAppParams = __Infer<typeof CreateAppReducer>;
export type CreateAppVersionParams = __Infer<typeof CreateAppVersionReducer>;
export type CreatePageParams = __Infer<typeof CreatePageReducer>;
export type CreatePageBlockParams = __Infer<typeof CreatePageBlockReducer>;
export type DeleteAppParams = __Infer<typeof DeleteAppReducer>;
export type DeletePageParams = __Infer<typeof DeletePageReducer>;
export type DeletePageBlockParams = __Infer<typeof DeletePageBlockReducer>;
export type InvokeToolRequestParams = __Infer<typeof InvokeToolRequestReducer>;
export type LinkOauthParams = __Infer<typeof LinkOauthReducer>;
export type MarkAgentMessageDeliveredParams = __Infer<typeof MarkAgentMessageDeliveredReducer>;
export type MarkDmReadParams = __Infer<typeof MarkDmReadReducer>;
export type RecordHealthCheckParams = __Infer<typeof RecordHealthCheckReducer>;
export type RecordPlatformEventParams = __Infer<typeof RecordPlatformEventReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RegisterToolParams = __Infer<typeof RegisterToolReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type ReorderPageBlocksParams = __Infer<typeof ReorderPageBlocksReducer>;
export type RestoreAppParams = __Infer<typeof RestoreAppReducer>;
export type SendAgentMessageParams = __Infer<typeof SendAgentMessageReducer>;
export type SendAppMessageParams = __Infer<typeof SendAppMessageReducer>;
export type SendDmParams = __Infer<typeof SendDmReducer>;
export type UnregisterAgentParams = __Infer<typeof UnregisterAgentReducer>;
export type UnregisterToolParams = __Infer<typeof UnregisterToolReducer>;
export type UpdateAppParams = __Infer<typeof UpdateAppReducer>;
export type UpdateAppStatusParams = __Infer<typeof UpdateAppStatusReducer>;
export type UpdateCodeSessionParams = __Infer<typeof UpdateCodeSessionReducer>;
export type UpdatePageParams = __Infer<typeof UpdatePageReducer>;
export type UpdatePageBlockParams = __Infer<typeof UpdatePageBlockReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

