// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  appId: __t.u64().name("app_id"),
  version: __t.u32(),
  codeHash: __t.string().name("code_hash"),
  changeDescription: __t.string().name("change_description"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.u64().name("created_at"),
});
