// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  handle: __t.string(),
  displayName: __t.string().name("display_name"),
  email: __t.string(),
  role: __t.string(),
  avatarUrl: __t.string().name("avatar_url"),
  online: __t.bool(),
  lastSeen: __t.u64().name("last_seen"),
  createdAt: __t.u64().name("created_at"),
});
